// This file was generated by liblab | https://liblab.com/

export interface ScoreAWordOrSentence1Params {
  key?: string;
  dialect?: string;
  userId?: string;
  __?: string;
}

export interface ScoreAPhonemeList1Params {
  key?: string;
  userId?: string;
  dialect?: string;
}

export interface ValidateText1Params {
  key?: string;
  text?: string;
  dialect?: string;
}

export interface TranscribeScore1Params {
  key?: string;
  dialect?: string;
  userId?: string;
}
