// This file was generated by liblab | https://liblab.com/

export type { AssessRelevance1Request } from './models/AssessRelevance1Request';
export type { AssessRelevance1Response } from './models/AssessRelevance1Response';
export type { ScoreAPhonemeList1Request } from './models/ScoreAPhonemeList1Request';
export type { ScoreAPhonemeList1Response } from './models/ScoreAPhonemeList1Response';
export type { ScoreVocabularyGrammarRequest } from './models/ScoreVocabularyGrammarRequest';
export type { ScoreVocabularyGrammarResponse } from './models/ScoreVocabularyGrammarResponse';
export type { ValidateText1Request } from './models/ValidateText1Request';
export type { ValidateText1Response } from './models/ValidateText1Response';
