// This file was generated by liblab | https://liblab.com/

export interface GetGrammarVocabCoherenceFeedbackMetricsResponse {
  quota_remaining?: number;
  speech_score?: SpeechScore;
  status?: string;
  version?: string;
}
interface SpeechScore {
  asr_version?: string;
  cefr_score?: CefrScore;
  coherence?: Coherence;
  fluency?: Fluency;
  grammar?: Grammar;
  ielts_score?: IeltsScore1;
  pte_score?: PteScore1;
  speechace_score?: SpeechaceScore1;
  toeic_score?: ToeicScore1;
  transcript?: string;
  vocab?: Vocab;
  word_score_list?: {
    ending_punctuation?: string;
    phone_score_list?: {
      extent?: number[];
      phone?: string;
      predicted_stress_level?: number;
      quality_score?: number;
      sound_most_like?: string;
      stress_level?: number;
      stress_score?: number;
      word_extent?: number[];
    }[];
    quality_score?: number;
    syllable_score_list?: {
      extent?: number[];
      letters?: string;
      phone_count?: number;
      predicted_stress_level?: number;
      quality_score?: number;
      stress_level?: number;
      stress_score?: number;
    }[];
    word?: string;
  }[];
}
interface CefrScore {
  coherence?: string;
  fluency?: string;
  grammar?: string;
  overall?: string;
  pronunciation?: string;
  vocab?: string;
}
interface Coherence {
  overall_metrics?: OverallMetrics;
}
interface OverallMetrics {
  adverb_diversity?: AdverbDiversity;
  basic_connectives?: BasicConnectives;
  causal_connectives?: CausalConnectives;
  lexical_density?: LexicalDensity;
  negative_connectives?: NegativeConnectives;
  pronoun_density?: PronounDensity;
  verb_diversity?: VerbDiversity;
}
interface AdverbDiversity {
  level?: string;
  score?: number;
}
interface BasicConnectives {
  examples?: string[];
  level?: string;
  score?: number;
}
interface CausalConnectives {
  level?: string;
  score?: number;
}
interface LexicalDensity {
  level?: string;
  score?: number;
}
interface NegativeConnectives {
  examples?: string[];
  level?: string;
  message?: string;
  score?: number;
}
interface PronounDensity {
  level?: string;
  score?: number;
}
interface VerbDiversity {
  level?: string;
  score?: number;
}
interface Fluency {
  fluency_version?: string;
  ielts_subscore_version?: string;
  overall_metrics?: OverallMetrics1;
  segment_metrics_list?: {
    all_pause_count?: number;
    all_pause_duration?: number;
    all_pause_list?: number[][];
    articulation_length?: number;
    articulation_rate?: number;
    cefr_score?: CefrScore1;
    correct_syllable_count?: number;
    correct_word_count?: number;
    duration?: number;
    ielts_score?: IeltsScore;
    max_length_run?: number;
    mean_length_run?: number;
    pte_score?: PteScore;
    segment?: number[];
    speech_rate?: number;
    speechace_score?: SpeechaceScore;
    syllable_correct_per_minute?: number;
    syllable_count?: number;
    toeic_score?: ToeicScore;
    word_correct_per_minute?: number;
    word_count?: number;
  }[];
}
interface OverallMetrics1 {
  all_pause_count?: number;
  all_pause_duration?: number;
  all_pause_list?: number[][];
  articulation_length?: number;
  articulation_rate?: number;
  correct_syllable_count?: number;
  correct_word_count?: number;
  duration?: number;
  max_length_run?: number;
  mean_length_run?: number;
  segment?: number[];
  speech_rate?: number;
  syllable_correct_per_minute?: number;
  syllable_count?: number;
  word_correct_per_minute?: number;
  word_count?: number;
}
interface CefrScore1 {
  coherence?: string;
  fluency?: string;
  grammar?: string;
  pronunciation?: string;
  vocab?: string;
}
interface IeltsScore {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  pronunciation?: number;
  vocab?: number;
}
interface PteScore {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  pronunciation?: number;
  vocab?: number;
}
interface SpeechaceScore {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  pronunciation?: number;
  vocab?: number;
}
interface ToeicScore {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  pronunciation?: number;
  vocab?: number;
}
interface Grammar {
  errors?: {
    category?: string;
    matched_text?: string;
    message?: string;
    replacements?: string[];
    span?: number[];
  }[];
  overall_metrics?: OverallMetrics2;
}
interface OverallMetrics2 {
  grammatical_accuracy?: GrammaticalAccuracy;
  grammatical_range?: GrammaticalRange;
  length?: Length;
  lexical_diversity?: LexicalDiversity;
}
interface GrammaticalAccuracy {
  level?: string;
  score?: number;
}
interface GrammaticalRange {
  adverb_modifier_variation?: AdverbModifierVariation;
  level?: string;
  message?: string;
  noun_phrase_complexity?: NounPhraseComplexity;
  noun_phrase_variation?: NounPhraseVariation;
  score?: number;
  verb_construction_variation?: VerbConstructionVariation;
}
interface AdverbModifierVariation {
  level?: string;
  score?: number;
}
interface NounPhraseComplexity {
  level?: string;
  message?: string;
  score?: number;
}
interface NounPhraseVariation {
  level?: string;
  score?: number;
}
interface VerbConstructionVariation {
  level?: string;
  score?: number;
}
interface Length {
  level?: string;
  score?: number;
}
interface LexicalDiversity {
  level?: string;
  score?: number;
}
interface IeltsScore1 {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  overall?: number;
  pronunciation?: number;
  vocab?: number;
}
interface PteScore1 {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  overall?: number;
  pronunciation?: number;
  vocab?: number;
}
interface SpeechaceScore1 {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  overall?: number;
  pronunciation?: number;
  vocab?: number;
}
interface ToeicScore1 {
  coherence?: number;
  fluency?: number;
  grammar?: number;
  overall?: number;
  pronunciation?: number;
  vocab?: number;
}
interface Vocab {
  overall_metrics?: OverallMetrics3;
}
interface OverallMetrics3 {
  academic_language_use?: AcademicLanguageUse;
  collocation_commonality?: CollocationCommonality;
  idiomaticity?: Idiomaticity;
  lexical_diversity?: LexicalDiversity1;
  word_sophistication?: WordSophistication;
  word_specificity?: WordSpecificity;
}
interface AcademicLanguageUse {
  level?: string;
  message?: string;
  score?: number;
}
interface CollocationCommonality {
  level?: string;
  score?: number;
}
interface Idiomaticity {
  level?: string;
  score?: number;
}
interface LexicalDiversity1 {
  level?: string;
  score?: number;
}
interface WordSophistication {
  level?: string;
  score?: number;
}
interface WordSpecificity {
  level?: string;
  message?: string;
  score?: number;
}
