// This file was generated by liblab | https://liblab.com/

export interface PteAnswerQuestionResponse {
  quota_remaining?: number;
  status?: string;
  task_score?: TaskScore;
  version?: string;
}
interface TaskScore {
  score?: number;
  transcript?: string;
  version?: string;
  type_?: string;
}
