// This file was generated by liblab | https://liblab.com/

export interface PteAnswerQuestionRequest {
  /**
   * Default: 1
   * Whether to include scoring other aspects of the speech: Pronunciation, Fluency, Grammar, Vocab, Coherence.
   * Set to 0 if you only want to receive the task score.
   *
   *
   */
  include_speech_score?: string;
  /**
   * The question presented to the user.
   */
  task_question?: string;
  /**
   * The user audio file containing the speaker's response to the task.
   */
  user_audio_file?: import('fs').ReadStream | Buffer | File;
}
