// This file was generated by liblab | https://liblab.com/

export interface ScoreFluencySpanishRequest {
  /**
   * includes fluency scoring for this request.
   */
  include_fluency?: string;
  /**
   * Instructs Speechace to automatically infer expected pronunciation for unknown terms such names, places, etc.
   */
  include_unknown_words?: string;
  /**
   * Indicates no multiple choice type text used.
   */
  no_mc?: string;
  /**
   * One or more paragraphs of text to score.
   */
  text?: string;
  /**
   * file with user audio (wav, mp3, m4a, webm, ogg, aiff)
   */
  user_audio_file?: import('fs').ReadStream | Buffer | File;
}
