// This file was generated by liblab | https://liblab.com/

export interface ScoreAPhonemeListResponse {
  quota_remaining?: number;
  status?: string;
  version?: string;
  word_score?: WordScore;
}
interface WordScore {
  phone_score_list?: {
    extent?: number[];
    phone?: string;
    quality_score?: number;
    sound_most_like?: string;
    stress_level?: StressLevel;
  }[];
  quality_score?: number;
  word?: string;
}
interface StressLevel {
  [k: string]: unknown;
}
