// This file was generated by liblab | https://liblab.com/

export interface ScoreFluencySpanishResponse {
  quota_remaining?: number;
  status?: string;
  text_score?: TextScore;
  version?: string;
}
interface TextScore {
  cefr_score?: CefrScore;
  fluency?: Fluency;
  speechace_score?: SpeechaceScore1;
  text?: string;
  word_score_list?: {
    ending_punctuation?: string;
    phone_score_list?: {
      extent?: number[];
      phone?: string;
      quality_score?: number;
      sound_most_like?: string;
      stress_level?: StressLevel;
      word_extent?: number[];
    }[];
    quality_score?: number;
    syllable_score_list?: {
      extent?: number[];
      letters?: string;
      phone_count?: number;
      quality_score?: number;
      stress_level?: number;
    }[];
    word?: string;
  }[];
}
interface CefrScore {
  fluency?: string;
  pronunciation?: string;
}
interface Fluency {
  fluency_version?: FluencyVersion;
  overall_metrics?: OverallMetrics;
  segment_metrics_list?: {
    all_pause_count?: number;
    all_pause_duration?: number;
    all_pause_list?: number[][];
    articulation_length?: number;
    articulation_rate?: number;
    cefr_score?: CefrScore1;
    correct_syllable_count?: number;
    correct_word_count?: number;
    duration?: number;
    max_length_run?: number;
    mean_length_run?: number;
    segment?: number[];
    speech_rate?: number;
    speechace_score?: SpeechaceScore;
    syllable_correct_per_minute?: number;
    syllable_count?: number;
    word_correct_per_minute?: number;
    word_count?: number;
  }[];
}
interface FluencyVersion {
  [k: string]: unknown;
}
interface OverallMetrics {
  all_pause_count?: number;
  all_pause_duration?: number;
  all_pause_list?: number[][];
  articulation_length?: number;
  articulation_rate?: number;
  correct_syllable_count?: number;
  correct_word_count?: number;
  duration?: number;
  max_length_run?: number;
  mean_length_run?: number;
  segment?: number[];
  speech_rate?: number;
  syllable_correct_per_minute?: number;
  syllable_count?: number;
  word_correct_per_minute?: number;
  word_count?: number;
}
interface CefrScore1 {
  fluency?: string;
  pronunciation?: string;
}
interface SpeechaceScore {
  fluency?: number;
  pronunciation?: number;
}
interface SpeechaceScore1 {
  fluency?: number;
  pronunciation?: number;
}
interface StressLevel {
  [k: string]: unknown;
}
