// This file was generated by liblab | https://liblab.com/

export interface ScoreAPhonemeListRequest {
  /**
   * A phoneme list to score.
   */
  phone_list?: string;
  /**
   * A unique identifier for the activity or question this user audio is answering.
   */
  question_info?: string;
  /**
   * file with user audio (wav, mp3, m4a, webm, ogg, aiff)
   */
  user_audio_file?: import('fs').ReadStream | Buffer | File;
}
