// This file was generated by liblab | https://liblab.com/

export interface ScoreAWordOrSentenceParams {
  key?: string;
  dialect?: string;
  userId?: string;
  __?: string;
}

export interface ScoreAPhonemeListParams {
  key?: string;
  userId?: string;
  dialect?: string;
}

export interface ValidateTextParams {
  key?: string;
  text?: string;
  dialect?: string;
}

export interface ScoreTaskParams {
  key?: string;
  taskType?: string;
  dialect?: string;
}

export interface TranscribeScoreParams {
  key?: string;
  dialect?: string;
  userId?: string;
}
