// This file was generated by liblab | https://liblab.com/

import nock from 'nock';

import { Speechaceapi } from '../../../src';

import { V1V7OlderVersionsService } from '../../../src/services/v1V7OlderVersions/V1V7OlderVersions';

describe('test V1V7OlderVersionsService object', () => {
  it('should be an object', () => {
    expect(typeof V1V7OlderVersionsService).toBe('function');
  });
});

describe('test V1V7OlderVersions', () => {
  let sdk: any;

  beforeEach(() => {
    sdk = new Speechaceapi();

    nock.cleanAll();
  });

  describe('test scoreVocabularyGrammar', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post('/api/scoring/text/v0.5/json?key=culpa&user_id=4770287755&dialect=ex')
        .reply(200, { data: {} });
      return sdk.v1V7OlderVersions
        .scoreVocabularyGrammar({}, { key: 'culpa', userId: '4770287755', dialect: 'ex' })
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });

  describe('test scoreAPhonemeList1', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post('/api/scoring/phone_list/v0.5/json?key=harum&user_id=8974372114&dialect=facilis')
        .reply(200, { data: {} });
      return sdk.v1V7OlderVersions
        .scoreAPhonemeList1({}, { key: 'harum', userId: '8974372114', dialect: 'facilis' })
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });

  describe('test validateText1', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post(
          '/api/validating/text/v0.5/json?key=fugit&text=officiasedundelaboriosammollitia&dialect=nam',
        )
        .reply(200, { data: {} });
      return sdk.v1V7OlderVersions
        .validateText1(
          {},
          { key: 'fugit', text: 'officiasedundelaboriosammollitia', dialect: 'nam' },
        )
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });

  describe('test assessRelevance1', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post('/api/scoring/speech/v0.5/json?key=occaecati&dialect=nobis&user_id=5696202847')
        .reply(200, { data: {} });
      return sdk.v1V7OlderVersions
        .assessRelevance1({}, { key: 'occaecati', dialect: 'nobis', userId: '5696202847' })
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });
});
