// This file was generated by liblab | https://liblab.com/

import { Speechaceapi } from 'speechaceapi';

(async () => {
  const speechaceapi = new Speechaceapi({});

  const input = {};

  const { data } = await speechaceapi.v9Latest_.validateText(input, {
    key: '{{speechacekey}}',
    text: '"Validate these words existeee."',
    dialect: 'en-us',
  });

  console.log(data);
})();
