// This file was generated by liblab | https://liblab.com/

import nock from 'nock';

import { Speechaceapi } from '../../../src';

import { V9LatestService } from '../../../src/services/v9Latest/V9Latest';

describe('test V9LatestService object', () => {
  it('should be an object', () => {
    expect(typeof V9LatestService).toBe('function');
  });
});

describe('test V9Latest', () => {
  let sdk: any;

  beforeEach(() => {
    sdk = new Speechaceapi();

    nock.cleanAll();
  });

  describe('test scoreFluencySpanish', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post('/api/scoring/text/v9/json?key=sit&dialect=tenetur')
        .reply(200, { data: {} });
      return sdk.v9Latest
        .scoreFluencySpanish({}, { key: 'sit', dialect: 'tenetur' })
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });

  describe('test scoreAPhonemeList', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post('/api/scoring/phone_list/v9/json?key=ipsa&user_id=4175261947&dialect=nihil')
        .reply(200, { data: {} });
      return sdk.v9Latest
        .scoreAPhonemeList({}, { key: 'ipsa', userId: '4175261947', dialect: 'nihil' })
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });

  describe('test validateText', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post(
          '/api/validating/text/v9/json?key=beatae&text=inciduntexquisquamlaborumquis&dialect=reiciendis',
        )
        .reply(200, { data: {} });
      return sdk.v9Latest
        .validateText(
          {},
          { key: 'beatae', text: 'inciduntexquisquamlaborumquis', dialect: 'reiciendis' },
        )
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });

  describe('test pteAnswerQuestion', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post('/api/scoring/task/v9/json?key=deserunt&task_type=placeat&dialect=molestias')
        .reply(200, { data: {} });
      return sdk.v9Latest
        .pteAnswerQuestion({}, { key: 'deserunt', taskType: 'placeat', dialect: 'molestias' })
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });

  describe('test getGrammarVocabCoherenceFeedbackMetrics', () => {
    test('test api call', () => {
      const scope = nock('https://api.speechace.co')
        .post('/api/scoring/speech/v9/json?key=mollitia&user_id=7011915748&dialect=in')
        .reply(200, { data: {} });
      return sdk.v9Latest
        .getGrammarVocabCoherenceFeedbackMetrics(
          {},
          { key: 'mollitia', userId: '7011915748', dialect: 'in' },
        )
        .then((r: any) => expect(r.data).toEqual({}));
    });
  });
});
