// This file was generated by liblab | https://liblab.com/

export interface AssessRelevance1Request {
  /**
   * includes fluency scoring for this request. To use this field you must have a Speechace API PRO key.
   */
  include_fluency?: string;
  /**
   * include IELTS subscores for (Vocabulary, Grammar, Coherence).
   */
  include_ielts_subscore?: string;
  /**
   * automatically identify the phonetic mapping for any unknown words such as names or locations and use that for scoring.
   */
  include_unknown_words?: string;
  /**
   * Question Prompt text provided to the user. When this parameter is passed, the relevance of the user audio transcript is evaluated for the given question prompt and a resulting relevance class is returned in .speech_score.relevance.class (TRUE/FALSE). A FALSE relevance class will result in .speech_score.fluency.overall_metrics.ielts_estimate and .speech_score.fluency.overall_metrics.pte_estimate to be set to the lowest possible score.
   */
  relevance_context?: string;
  /**
   * file with user audio (wav, mp3, m4a, webm, ogg, aiff)
   */
  user_audio_file?: import('fs').ReadStream | Buffer | File;
}
