// This file was generated by liblab | https://liblab.com/

export interface AssessRelevance1Response {
  quota_remaining?: number;
  speech_score?: SpeechScore;
  status?: string;
  version?: string;
}
interface SpeechScore {
  fidelity_class?: string;
  fluency?: Fluency;
  quality_score?: number;
  relevance?: Relevance;
  transcript?: string;
  word_score_list?: {
    ending_punctuation?: string;
    phone_score_list?: {
      extent?: number[];
      phone?: string;
      quality_score?: number;
      sound_most_like?: string;
      stress_level?: number;
      stress_score?: number;
    }[];
    quality_score?: number;
    syllable_score_list?: {
      extent?: number[];
      letters?: string;
      phone_count?: number;
      quality_score?: number;
      stress_level?: number;
      stress_score?: number;
    }[];
    word?: string;
  }[];
}
interface Fluency {
  fluency_version?: FluencyVersion;
  ielts_subscore_version?: IeltsSubscoreVersion;
  overall_metrics?: OverallMetrics;
  segment_metrics_list?: {
    all_pause_count?: number;
    all_pause_duration?: number;
    all_pause_list?: number[][];
    articulation_length?: number;
    articulation_rate?: number;
    correct_syllable_count?: number;
    correct_word_count?: number;
    duration?: number;
    fluency_score?: number;
    ielts_estimate?: number;
    ielts_subscore?: IeltsSubscore1;
    max_length_run?: number;
    mean_length_run?: number;
    pte_estimate?: number;
    segment?: number[];
    speech_rate?: number;
    syllable_correct_per_minute?: number;
    syllable_count?: number;
    word_correct_per_minute?: number;
    word_count?: number;
  }[];
}
interface FluencyVersion {
  [k: string]: unknown;
}
interface IeltsSubscoreVersion {
  [k: string]: unknown;
}
interface OverallMetrics {
  all_pause_count?: number;
  all_pause_duration?: number;
  all_pause_list?: number[][];
  articulation_length?: number;
  articulation_rate?: number;
  correct_syllable_count?: number;
  correct_word_count?: number;
  duration?: number;
  fluency_score?: number;
  ielts_estimate?: number;
  ielts_subscore?: IeltsSubscore;
  max_length_run?: number;
  mean_length_run?: number;
  pte_estimate?: number;
  segment?: number[];
  speech_rate?: number;
  syllable_correct_per_minute?: number;
  syllable_count?: number;
  word_correct_per_minute?: number;
  word_count?: number;
}
interface IeltsSubscore {
  coherence?: number;
  grammar?: number;
  vocab?: number;
}
interface IeltsSubscore1 {
  coherence?: number;
  grammar?: number;
  vocab?: number;
}
interface Relevance {
  class_?: string;
}
