// This file was generated by liblab | https://liblab.com/

export interface ScoreVocabularyGrammarRequest {
  /**
   * includes fluency scoring for this request. To use this field you must have a Speechace API PRO key.
   */
  include_fluency?: string;
  /**
   * beta: include IELTS subscores for (Vocabulary, Grammar).
   */
  include_ielts_subscore?: string;
  /**
   * A unique identifier for the activity or question this user audio is answering.
   *
   * Structure this field to include as much info as possible to aid in reporting and analytics.
   *
   * For example: **question_info='u1/q1'** where:
   *
   * * u1: means the question belongs to Unit 1 in your content
   * * q1: means this is question 1 within the unit
   *
   * You can add more levels as needed.
   *
   * Ensure  **no personally identifiable information** is passed in this field.
   */
  question_info?: string;
  /**
   * One or more paragraphs of text to score.
   */
  text?: string;
  /**
   * file with user audio (wav, mp3, m4a, webm, ogg, aiff)
   */
  user_audio_file?: import('fs').ReadStream | Buffer | File;
}
