// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const grammaticalAccuracy = z.lazy(() => {
  return z.object({
    level: z.string().optional(),
    score: z.number().optional(),
  });
});

/**
 *
 * @typedef  {GrammaticalAccuracy} grammaticalAccuracy
 * @property {string}
 * @property {number}
 */
export type GrammaticalAccuracy = z.infer<typeof grammaticalAccuracy>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const grammaticalAccuracyResponse = z.lazy(() => {
  return z
    .object({
      level: z.string().optional(),
      score: z.number().optional(),
    })
    .transform((data) => ({
      level: data['level'],
      score: data['score'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const grammaticalAccuracyRequest = z.lazy(() => {
  return z.object({ level: z.string().nullish(), score: z.number().nullish() }).transform((data) => ({
    level: data['level'],
    score: data['score'],
  }));
});
