// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const scoreIssueList = z.lazy(() => {
  return z.object({
    detailMessage: z.string().optional(),
    shortMessage: z.string().optional(),
    source: z.string().optional(),
    status: z.string().optional(),
  });
});

/**
 *
 * @typedef  {ScoreIssueList} scoreIssueList
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 */
export type ScoreIssueList = z.infer<typeof scoreIssueList>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreIssueListResponse = z.lazy(() => {
  return z
    .object({
      detail_message: z.string().optional(),
      short_message: z.string().optional(),
      source: z.string().optional(),
      status: z.string().optional(),
    })
    .transform((data) => ({
      detailMessage: data['detail_message'],
      shortMessage: data['short_message'],
      source: data['source'],
      status: data['status'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreIssueListRequest = z.lazy(() => {
  return z
    .object({
      detailMessage: z.string().nullish(),
      shortMessage: z.string().nullish(),
      source: z.string().nullish(),
      status: z.string().nullish(),
    })
    .transform((data) => ({
      detail_message: data['detailMessage'],
      short_message: data['shortMessage'],
      source: data['source'],
      status: data['status'],
    }));
});
