// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  scoreAWordOrSentenceOkResponseTextScore,
  scoreAWordOrSentenceOkResponseTextScoreRequest,
  scoreAWordOrSentenceOkResponseTextScoreResponse,
} from './score-a-word-or-sentence-ok-response-text-score';

/**
 * The shape of the model inside the application code - what the users use
 */
export const scoreAWordOrSentenceOkResponse = z.lazy(() => {
  return z.object({
    quotaRemaining: z.number().optional(),
    status: z.string().optional(),
    textScore: scoreAWordOrSentenceOkResponseTextScore.optional(),
    version: z.string().optional(),
  });
});

/**
 *
 * @typedef  {ScoreAWordOrSentenceOkResponse} scoreAWordOrSentenceOkResponse
 * @property {number}
 * @property {string}
 * @property {ScoreAWordOrSentenceOkResponseTextScore}
 * @property {string}
 */
export type ScoreAWordOrSentenceOkResponse = z.infer<typeof scoreAWordOrSentenceOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAWordOrSentenceOkResponseResponse = z.lazy(() => {
  return z
    .object({
      quota_remaining: z.number().optional(),
      status: z.string().optional(),
      text_score: scoreAWordOrSentenceOkResponseTextScoreResponse.optional(),
      version: z.string().optional(),
    })
    .transform((data) => ({
      quotaRemaining: data['quota_remaining'],
      status: data['status'],
      textScore: data['text_score'],
      version: data['version'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAWordOrSentenceOkResponseRequest = z.lazy(() => {
  return z
    .object({
      quotaRemaining: z.number().nullish(),
      status: z.string().nullish(),
      textScore: scoreAWordOrSentenceOkResponseTextScoreRequest.nullish(),
      version: z.string().nullish(),
    })
    .transform((data) => ({
      quota_remaining: data['quotaRemaining'],
      status: data['status'],
      text_score: data['textScore'],
      version: data['version'],
    }));
});
