// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  wordScorePhoneScoreList1,
  wordScorePhoneScoreList1Request,
  wordScorePhoneScoreList1Response,
} from './word-score-phone-score-list-1';

/**
 * The shape of the model inside the application code - what the users use
 */
export const scoreAPhonemeListOkResponseWordScore = z.lazy(() => {
  return z.object({
    phoneScoreList: z.array(wordScorePhoneScoreList1).optional(),
    qualityScore: z.number().optional(),
    word: z.string().optional(),
  });
});

/**
 *
 * @typedef  {ScoreAPhonemeListOkResponseWordScore} scoreAPhonemeListOkResponseWordScore
 * @property {WordScorePhoneScoreList1[]}
 * @property {number}
 * @property {string}
 */
export type ScoreAPhonemeListOkResponseWordScore = z.infer<typeof scoreAPhonemeListOkResponseWordScore>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAPhonemeListOkResponseWordScoreResponse = z.lazy(() => {
  return z
    .object({
      phone_score_list: z.array(wordScorePhoneScoreList1Response).optional(),
      quality_score: z.number().optional(),
      word: z.string().optional(),
    })
    .transform((data) => ({
      phoneScoreList: data['phone_score_list'],
      qualityScore: data['quality_score'],
      word: data['word'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAPhonemeListOkResponseWordScoreRequest = z.lazy(() => {
  return z
    .object({
      phoneScoreList: z.array(wordScorePhoneScoreList1Request).nullish(),
      qualityScore: z.number().nullish(),
      word: z.string().nullish(),
    })
    .transform((data) => ({
      phone_score_list: data['phoneScoreList'],
      quality_score: data['qualityScore'],
      word: data['word'],
    }));
});
