// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  scoreAPhonemeListOkResponseWordScore,
  scoreAPhonemeListOkResponseWordScoreRequest,
  scoreAPhonemeListOkResponseWordScoreResponse,
} from './score-a-phoneme-list-ok-response-word-score';

/**
 * The shape of the model inside the application code - what the users use
 */
export const scoreAPhonemeListOkResponse = z.lazy(() => {
  return z.object({
    quotaRemaining: z.number().optional(),
    status: z.string().optional(),
    version: z.string().optional(),
    wordScore: scoreAPhonemeListOkResponseWordScore.optional(),
  });
});

/**
 *
 * @typedef  {ScoreAPhonemeListOkResponse} scoreAPhonemeListOkResponse
 * @property {number}
 * @property {string}
 * @property {string}
 * @property {ScoreAPhonemeListOkResponseWordScore}
 */
export type ScoreAPhonemeListOkResponse = z.infer<typeof scoreAPhonemeListOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAPhonemeListOkResponseResponse = z.lazy(() => {
  return z
    .object({
      quota_remaining: z.number().optional(),
      status: z.string().optional(),
      version: z.string().optional(),
      word_score: scoreAPhonemeListOkResponseWordScoreResponse.optional(),
    })
    .transform((data) => ({
      quotaRemaining: data['quota_remaining'],
      status: data['status'],
      version: data['version'],
      wordScore: data['word_score'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAPhonemeListOkResponseRequest = z.lazy(() => {
  return z
    .object({
      quotaRemaining: z.number().nullish(),
      status: z.string().nullish(),
      version: z.string().nullish(),
      wordScore: scoreAPhonemeListOkResponseWordScoreRequest.nullish(),
    })
    .transform((data) => ({
      quota_remaining: data['quotaRemaining'],
      status: data['status'],
      version: data['version'],
      word_score: data['wordScore'],
    }));
});
