// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const segmentMetricsListSpeechaceScore2 = z.lazy(() => {
  return z.object({
    coherence: z.number().optional(),
    fluency: z.number().optional(),
    grammar: z.number().optional(),
    pronunciation: z.number().optional(),
    vocab: z.number().optional(),
  });
});

/**
 *
 * @typedef  {SegmentMetricsListSpeechaceScore2} segmentMetricsListSpeechaceScore2
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 */
export type SegmentMetricsListSpeechaceScore2 = z.infer<typeof segmentMetricsListSpeechaceScore2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const segmentMetricsListSpeechaceScore2Response = z.lazy(() => {
  return z
    .object({
      coherence: z.number().optional(),
      fluency: z.number().optional(),
      grammar: z.number().optional(),
      pronunciation: z.number().optional(),
      vocab: z.number().optional(),
    })
    .transform((data) => ({
      coherence: data['coherence'],
      fluency: data['fluency'],
      grammar: data['grammar'],
      pronunciation: data['pronunciation'],
      vocab: data['vocab'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const segmentMetricsListSpeechaceScore2Request = z.lazy(() => {
  return z
    .object({
      coherence: z.number().nullish(),
      fluency: z.number().nullish(),
      grammar: z.number().nullish(),
      pronunciation: z.number().nullish(),
      vocab: z.number().nullish(),
    })
    .transform((data) => ({
      coherence: data['coherence'],
      fluency: data['fluency'],
      grammar: data['grammar'],
      pronunciation: data['pronunciation'],
      vocab: data['vocab'],
    }));
});
