// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  fluencyOverallMetrics1,
  fluencyOverallMetrics1Request,
  fluencyOverallMetrics1Response,
} from './fluency-overall-metrics-1';
import {
  fluencySegmentMetricsList1,
  fluencySegmentMetricsList1Request,
  fluencySegmentMetricsList1Response,
} from './fluency-segment-metrics-list-1';

/**
 * The shape of the model inside the application code - what the users use
 */
export const textScoreFluency1 = z.lazy(() => {
  return z.object({
    fluencyVersion: z.any().optional().nullable(),
    overallMetrics: fluencyOverallMetrics1.optional(),
    segmentMetricsList: z.array(fluencySegmentMetricsList1).optional(),
  });
});

/**
 *
 * @typedef  {TextScoreFluency1} textScoreFluency1
 * @property {any}
 * @property {FluencyOverallMetrics1}
 * @property {FluencySegmentMetricsList1[]}
 */
export type TextScoreFluency1 = z.infer<typeof textScoreFluency1>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const textScoreFluency1Response = z.lazy(() => {
  return z
    .object({
      fluency_version: z.any().optional().nullable(),
      overall_metrics: fluencyOverallMetrics1Response.optional(),
      segment_metrics_list: z.array(fluencySegmentMetricsList1Response).optional(),
    })
    .transform((data) => ({
      fluencyVersion: data['fluency_version'],
      overallMetrics: data['overall_metrics'],
      segmentMetricsList: data['segment_metrics_list'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const textScoreFluency1Request = z.lazy(() => {
  return z
    .object({
      fluencyVersion: z.any().nullish(),
      overallMetrics: fluencyOverallMetrics1Request.nullish(),
      segmentMetricsList: z.array(fluencySegmentMetricsList1Request).nullish(),
    })
    .transform((data) => ({
      fluency_version: data['fluencyVersion'],
      overall_metrics: data['overallMetrics'],
      segment_metrics_list: data['segmentMetricsList'],
    }));
});
