// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  wordScoreListPhoneScoreList1,
  wordScoreListPhoneScoreList1Request,
  wordScoreListPhoneScoreList1Response,
} from './word-score-list-phone-score-list-1';
import {
  wordScoreListSyllableScoreList1,
  wordScoreListSyllableScoreList1Request,
  wordScoreListSyllableScoreList1Response,
} from './word-score-list-syllable-score-list-1';

/**
 * The shape of the model inside the application code - what the users use
 */
export const textScoreWordScoreList1 = z.lazy(() => {
  return z.object({
    phoneScoreList: z.array(wordScoreListPhoneScoreList1).optional(),
    qualityScore: z.number().optional(),
    syllableScoreList: z.array(wordScoreListSyllableScoreList1).optional(),
    word: z.string().optional(),
  });
});

/**
 *
 * @typedef  {TextScoreWordScoreList1} textScoreWordScoreList1
 * @property {WordScoreListPhoneScoreList1[]}
 * @property {number}
 * @property {WordScoreListSyllableScoreList1[]}
 * @property {string}
 */
export type TextScoreWordScoreList1 = z.infer<typeof textScoreWordScoreList1>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const textScoreWordScoreList1Response = z.lazy(() => {
  return z
    .object({
      phone_score_list: z.array(wordScoreListPhoneScoreList1Response).optional(),
      quality_score: z.number().optional(),
      syllable_score_list: z.array(wordScoreListSyllableScoreList1Response).optional(),
      word: z.string().optional(),
    })
    .transform((data) => ({
      phoneScoreList: data['phone_score_list'],
      qualityScore: data['quality_score'],
      syllableScoreList: data['syllable_score_list'],
      word: data['word'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const textScoreWordScoreList1Request = z.lazy(() => {
  return z
    .object({
      phoneScoreList: z.array(wordScoreListPhoneScoreList1Request).nullish(),
      qualityScore: z.number().nullish(),
      syllableScoreList: z.array(wordScoreListSyllableScoreList1Request).nullish(),
      word: z.string().nullish(),
    })
    .transform((data) => ({
      phone_score_list: data['phoneScoreList'],
      quality_score: data['qualityScore'],
      syllable_score_list: data['syllableScoreList'],
      word: data['word'],
    }));
});
