// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const wordScorePhoneScoreList1 = z.lazy(() => {
  return z.object({
    extent: z.array(z.number()).optional(),
    phone: z.string().optional(),
    qualityScore: z.number().optional(),
    soundMostLike: z.string().optional(),
    stressLevel: z.any().optional().nullable(),
  });
});

/**
 *
 * @typedef  {WordScorePhoneScoreList1} wordScorePhoneScoreList1
 * @property {number[]}
 * @property {string}
 * @property {number}
 * @property {string}
 * @property {any}
 */
export type WordScorePhoneScoreList1 = z.infer<typeof wordScorePhoneScoreList1>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const wordScorePhoneScoreList1Response = z.lazy(() => {
  return z
    .object({
      extent: z.array(z.number()).optional(),
      phone: z.string().optional(),
      quality_score: z.number().optional(),
      sound_most_like: z.string().optional(),
      stress_level: z.any().optional().nullable(),
    })
    .transform((data) => ({
      extent: data['extent'],
      phone: data['phone'],
      qualityScore: data['quality_score'],
      soundMostLike: data['sound_most_like'],
      stressLevel: data['stress_level'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const wordScorePhoneScoreList1Request = z.lazy(() => {
  return z
    .object({
      extent: z.array(z.number()).nullish(),
      phone: z.string().nullish(),
      qualityScore: z.number().nullish(),
      soundMostLike: z.string().nullish(),
      stressLevel: z.any().nullish(),
    })
    .transform((data) => ({
      extent: data['extent'],
      phone: data['phone'],
      quality_score: data['qualityScore'],
      sound_most_like: data['soundMostLike'],
      stress_level: data['stressLevel'],
    }));
});
