// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  segmentMetricsListIeltsSubscore,
  segmentMetricsListIeltsSubscoreRequest,
  segmentMetricsListIeltsSubscoreResponse,
} from './segment-metrics-list-ielts-subscore';

/**
 * The shape of the model inside the application code - what the users use
 */
export const fluencySegmentMetricsList4 = z.lazy(() => {
  return z.object({
    allPauseCount: z.number().optional(),
    allPauseDuration: z.number().optional(),
    allPauseList: z.array(z.array(z.number())).optional(),
    articulationLength: z.number().optional(),
    articulationRate: z.number().optional(),
    correctSyllableCount: z.number().optional(),
    correctWordCount: z.number().optional(),
    duration: z.number().optional(),
    fluencyScore: z.number().optional(),
    ieltsEstimate: z.number().optional(),
    ieltsSubscore: segmentMetricsListIeltsSubscore.optional(),
    maxLengthRun: z.number().optional(),
    meanLengthRun: z.number().optional(),
    pteEstimate: z.number().optional(),
    segment: z.array(z.number()).optional(),
    speechRate: z.number().optional(),
    syllableCorrectPerMinute: z.number().optional(),
    syllableCount: z.number().optional(),
    wordCorrectPerMinute: z.number().optional(),
    wordCount: z.number().optional(),
  });
});

/**
 *
 * @typedef  {FluencySegmentMetricsList4} fluencySegmentMetricsList4
 * @property {number}
 * @property {number}
 * @property {number[][]}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {SegmentMetricsListIeltsSubscore}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number[]}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 * @property {number}
 */
export type FluencySegmentMetricsList4 = z.infer<typeof fluencySegmentMetricsList4>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const fluencySegmentMetricsList4Response = z.lazy(() => {
  return z
    .object({
      all_pause_count: z.number().optional(),
      all_pause_duration: z.number().optional(),
      all_pause_list: z.array(z.array(z.number())).optional(),
      articulation_length: z.number().optional(),
      articulation_rate: z.number().optional(),
      correct_syllable_count: z.number().optional(),
      correct_word_count: z.number().optional(),
      duration: z.number().optional(),
      fluency_score: z.number().optional(),
      ielts_estimate: z.number().optional(),
      ielts_subscore: segmentMetricsListIeltsSubscoreResponse.optional(),
      max_length_run: z.number().optional(),
      mean_length_run: z.number().optional(),
      pte_estimate: z.number().optional(),
      segment: z.array(z.number()).optional(),
      speech_rate: z.number().optional(),
      syllable_correct_per_minute: z.number().optional(),
      syllable_count: z.number().optional(),
      word_correct_per_minute: z.number().optional(),
      word_count: z.number().optional(),
    })
    .transform((data) => ({
      allPauseCount: data['all_pause_count'],
      allPauseDuration: data['all_pause_duration'],
      allPauseList: data['all_pause_list'],
      articulationLength: data['articulation_length'],
      articulationRate: data['articulation_rate'],
      correctSyllableCount: data['correct_syllable_count'],
      correctWordCount: data['correct_word_count'],
      duration: data['duration'],
      fluencyScore: data['fluency_score'],
      ieltsEstimate: data['ielts_estimate'],
      ieltsSubscore: data['ielts_subscore'],
      maxLengthRun: data['max_length_run'],
      meanLengthRun: data['mean_length_run'],
      pteEstimate: data['pte_estimate'],
      segment: data['segment'],
      speechRate: data['speech_rate'],
      syllableCorrectPerMinute: data['syllable_correct_per_minute'],
      syllableCount: data['syllable_count'],
      wordCorrectPerMinute: data['word_correct_per_minute'],
      wordCount: data['word_count'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const fluencySegmentMetricsList4Request = z.lazy(() => {
  return z
    .object({
      allPauseCount: z.number().nullish(),
      allPauseDuration: z.number().nullish(),
      allPauseList: z.array(z.array(z.number())).nullish(),
      articulationLength: z.number().nullish(),
      articulationRate: z.number().nullish(),
      correctSyllableCount: z.number().nullish(),
      correctWordCount: z.number().nullish(),
      duration: z.number().nullish(),
      fluencyScore: z.number().nullish(),
      ieltsEstimate: z.number().nullish(),
      ieltsSubscore: segmentMetricsListIeltsSubscoreRequest.nullish(),
      maxLengthRun: z.number().nullish(),
      meanLengthRun: z.number().nullish(),
      pteEstimate: z.number().nullish(),
      segment: z.array(z.number()).nullish(),
      speechRate: z.number().nullish(),
      syllableCorrectPerMinute: z.number().nullish(),
      syllableCount: z.number().nullish(),
      wordCorrectPerMinute: z.number().nullish(),
      wordCount: z.number().nullish(),
    })
    .transform((data) => ({
      all_pause_count: data['allPauseCount'],
      all_pause_duration: data['allPauseDuration'],
      all_pause_list: data['allPauseList'],
      articulation_length: data['articulationLength'],
      articulation_rate: data['articulationRate'],
      correct_syllable_count: data['correctSyllableCount'],
      correct_word_count: data['correctWordCount'],
      duration: data['duration'],
      fluency_score: data['fluencyScore'],
      ielts_estimate: data['ieltsEstimate'],
      ielts_subscore: data['ieltsSubscore'],
      max_length_run: data['maxLengthRun'],
      mean_length_run: data['meanLengthRun'],
      pte_estimate: data['pteEstimate'],
      segment: data['segment'],
      speech_rate: data['speechRate'],
      syllable_correct_per_minute: data['syllableCorrectPerMinute'],
      syllable_count: data['syllableCount'],
      word_correct_per_minute: data['wordCorrectPerMinute'],
      word_count: data['wordCount'],
    }));
});
