// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  scoreAWordOrSentence1OkResponseTextScore,
  scoreAWordOrSentence1OkResponseTextScoreRequest,
  scoreAWordOrSentence1OkResponseTextScoreResponse,
} from './score-a-word-or-sentence1-ok-response-text-score';

/**
 * The shape of the model inside the application code - what the users use
 */
export const scoreAWordOrSentence1OkResponse = z.lazy(() => {
  return z.object({
    quotaRemaining: z.number().optional(),
    status: z.string().optional(),
    textScore: scoreAWordOrSentence1OkResponseTextScore.optional(),
    version: z.string().optional(),
  });
});

/**
 *
 * @typedef  {ScoreAWordOrSentence1OkResponse} scoreAWordOrSentence1OkResponse
 * @property {number}
 * @property {string}
 * @property {ScoreAWordOrSentence1OkResponseTextScore}
 * @property {string}
 */
export type ScoreAWordOrSentence1OkResponse = z.infer<typeof scoreAWordOrSentence1OkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAWordOrSentence1OkResponseResponse = z.lazy(() => {
  return z
    .object({
      quota_remaining: z.number().optional(),
      status: z.string().optional(),
      text_score: scoreAWordOrSentence1OkResponseTextScoreResponse.optional(),
      version: z.string().optional(),
    })
    .transform((data) => ({
      quotaRemaining: data['quota_remaining'],
      status: data['status'],
      textScore: data['text_score'],
      version: data['version'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const scoreAWordOrSentence1OkResponseRequest = z.lazy(() => {
  return z
    .object({
      quotaRemaining: z.number().nullish(),
      status: z.string().nullish(),
      textScore: scoreAWordOrSentence1OkResponseTextScoreRequest.nullish(),
      version: z.string().nullish(),
    })
    .transform((data) => ({
      quota_remaining: data['quotaRemaining'],
      status: data['status'],
      text_score: data['textScore'],
      version: data['version'],
    }));
});
