// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  wordScoreListPhoneScoreList4,
  wordScoreListPhoneScoreList4Request,
  wordScoreListPhoneScoreList4Response,
} from './word-score-list-phone-score-list-4';
import {
  wordScoreListSyllableScoreList4,
  wordScoreListSyllableScoreList4Request,
  wordScoreListSyllableScoreList4Response,
} from './word-score-list-syllable-score-list-4';

/**
 * The shape of the model inside the application code - what the users use
 */
export const speechScoreWordScoreList2 = z.lazy(() => {
  return z.object({
    endingPunctuation: z.string().optional(),
    phoneScoreList: z.array(wordScoreListPhoneScoreList4).optional(),
    qualityScore: z.number().optional(),
    syllableScoreList: z.array(wordScoreListSyllableScoreList4).optional(),
    word: z.string().optional(),
  });
});

/**
 *
 * @typedef  {SpeechScoreWordScoreList2} speechScoreWordScoreList2
 * @property {string}
 * @property {WordScoreListPhoneScoreList4[]}
 * @property {number}
 * @property {WordScoreListSyllableScoreList4[]}
 * @property {string}
 */
export type SpeechScoreWordScoreList2 = z.infer<typeof speechScoreWordScoreList2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const speechScoreWordScoreList2Response = z.lazy(() => {
  return z
    .object({
      ending_punctuation: z.string().optional(),
      phone_score_list: z.array(wordScoreListPhoneScoreList4Response).optional(),
      quality_score: z.number().optional(),
      syllable_score_list: z.array(wordScoreListSyllableScoreList4Response).optional(),
      word: z.string().optional(),
    })
    .transform((data) => ({
      endingPunctuation: data['ending_punctuation'],
      phoneScoreList: data['phone_score_list'],
      qualityScore: data['quality_score'],
      syllableScoreList: data['syllable_score_list'],
      word: data['word'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const speechScoreWordScoreList2Request = z.lazy(() => {
  return z
    .object({
      endingPunctuation: z.string().nullish(),
      phoneScoreList: z.array(wordScoreListPhoneScoreList4Request).nullish(),
      qualityScore: z.number().nullish(),
      syllableScoreList: z.array(wordScoreListSyllableScoreList4Request).nullish(),
      word: z.string().nullish(),
    })
    .transform((data) => ({
      ending_punctuation: data['endingPunctuation'],
      phone_score_list: data['phoneScoreList'],
      quality_score: data['qualityScore'],
      syllable_score_list: data['syllableScoreList'],
      word: data['word'],
    }));
});
