// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  fluencyOverallMetrics4,
  fluencyOverallMetrics4Request,
  fluencyOverallMetrics4Response,
} from './fluency-overall-metrics-4';
import {
  fluencySegmentMetricsList4,
  fluencySegmentMetricsList4Request,
  fluencySegmentMetricsList4Response,
} from './fluency-segment-metrics-list-4';

/**
 * The shape of the model inside the application code - what the users use
 */
export const speechScoreFluency2 = z.lazy(() => {
  return z.object({
    fluencyVersion: z.any().optional().nullable(),
    ieltsSubscoreVersion: z.any().optional().nullable(),
    overallMetrics: fluencyOverallMetrics4.optional(),
    segmentMetricsList: z.array(fluencySegmentMetricsList4).optional(),
  });
});

/**
 *
 * @typedef  {SpeechScoreFluency2} speechScoreFluency2
 * @property {any}
 * @property {any}
 * @property {FluencyOverallMetrics4}
 * @property {FluencySegmentMetricsList4[]}
 */
export type SpeechScoreFluency2 = z.infer<typeof speechScoreFluency2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const speechScoreFluency2Response = z.lazy(() => {
  return z
    .object({
      fluency_version: z.any().optional().nullable(),
      ielts_subscore_version: z.any().optional().nullable(),
      overall_metrics: fluencyOverallMetrics4Response.optional(),
      segment_metrics_list: z.array(fluencySegmentMetricsList4Response).optional(),
    })
    .transform((data) => ({
      fluencyVersion: data['fluency_version'],
      ieltsSubscoreVersion: data['ielts_subscore_version'],
      overallMetrics: data['overall_metrics'],
      segmentMetricsList: data['segment_metrics_list'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const speechScoreFluency2Request = z.lazy(() => {
  return z
    .object({
      fluencyVersion: z.any().nullish(),
      ieltsSubscoreVersion: z.any().nullish(),
      overallMetrics: fluencyOverallMetrics4Request.nullish(),
      segmentMetricsList: z.array(fluencySegmentMetricsList4Request).nullish(),
    })
    .transform((data) => ({
      fluency_version: data['fluencyVersion'],
      ielts_subscore_version: data['ieltsSubscoreVersion'],
      overall_metrics: data['overallMetrics'],
      segment_metrics_list: data['segmentMetricsList'],
    }));
});
