// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  fluencyOverallMetrics3,
  fluencyOverallMetrics3Request,
  fluencyOverallMetrics3Response,
} from './fluency-overall-metrics-3';
import {
  fluencySegmentMetricsList3,
  fluencySegmentMetricsList3Request,
  fluencySegmentMetricsList3Response,
} from './fluency-segment-metrics-list-3';

/**
 * The shape of the model inside the application code - what the users use
 */
export const textScoreFluency2 = z.lazy(() => {
  return z.object({
    fluencyVersion: z.any().optional().nullable(),
    ieltsSubscoreVersion: z.any().optional().nullable(),
    overallMetrics: fluencyOverallMetrics3.optional(),
    segmentMetricsList: z.array(fluencySegmentMetricsList3).optional(),
  });
});

/**
 *
 * @typedef  {TextScoreFluency2} textScoreFluency2
 * @property {any}
 * @property {any}
 * @property {FluencyOverallMetrics3}
 * @property {FluencySegmentMetricsList3[]}
 */
export type TextScoreFluency2 = z.infer<typeof textScoreFluency2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const textScoreFluency2Response = z.lazy(() => {
  return z
    .object({
      fluency_version: z.any().optional().nullable(),
      ielts_subscore_version: z.any().optional().nullable(),
      overall_metrics: fluencyOverallMetrics3Response.optional(),
      segment_metrics_list: z.array(fluencySegmentMetricsList3Response).optional(),
    })
    .transform((data) => ({
      fluencyVersion: data['fluency_version'],
      ieltsSubscoreVersion: data['ielts_subscore_version'],
      overallMetrics: data['overall_metrics'],
      segmentMetricsList: data['segment_metrics_list'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const textScoreFluency2Request = z.lazy(() => {
  return z
    .object({
      fluencyVersion: z.any().nullish(),
      ieltsSubscoreVersion: z.any().nullish(),
      overallMetrics: fluencyOverallMetrics3Request.nullish(),
      segmentMetricsList: z.array(fluencySegmentMetricsList3Request).nullish(),
    })
    .transform((data) => ({
      fluency_version: data['fluencyVersion'],
      ielts_subscore_version: data['ieltsSubscoreVersion'],
      overall_metrics: data['overallMetrics'],
      segment_metrics_list: data['segmentMetricsList'],
    }));
});
